version: '3'

services:

  chromedrive:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  redis:
    build:
      context: ./redis/

  crawler:
    image: crawler_image
    build:
      context: ./crawler/
    volumes:
      - ./crawler/crawlerServer:/code
    command: python manage.py runserver 0.0.0.0:8083
    restart: always
    ports:
      - 8083:8083
    links:
      - chromedrive
    depends_on:
      - redis

  qcluster:
    image: crawler_image
    volumes:
      - ./crawler/crawlerServer:/code
    command: python manage.py qcluster
    restart: always
    links:
      - chromedrive
    depends_on:
      - redis
      - crawler

  client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/app
    ports:
      - 3000:3000
    stdin_open: true # Cannot start react without this line

  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/app
    ports:
      - 4000:4000
      - 5000:5000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3456:3306
volumes:
  mysql:
